
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka}
  server:
     waitTimeInMsWhenSyncEmpty: 0
     renewal-percent-threshold: 0.49
  
